-- MySQL Script generated by MySQL Workbench
-- Sat Jun 17 13:57:31 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ShopTest
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ShopTest
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ShopTest` DEFAULT CHARACTER SET gb2312 ;
USE `ShopTest` ;

-- -----------------------------------------------------
-- Table `ShopTest`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShopTest`.`category` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '分类id',
  `name` VARCHAR(45) NULL COMMENT '分类名称',
  `small_text` VARCHAR(45) NULL COMMENT '分类简介\n',
  `create_time` INT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = gb2312
COMMENT = '分类表';


-- -----------------------------------------------------
-- Table `ShopTest`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShopTest`.`product` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '商品id',
  `name` VARCHAR(80) NULL COMMENT '商品名称',
  `original_price` FLOAT NULL COMMENT '商品价格',
  `deducted_price` FLOAT NULL,
  `unit` VARCHAR(1) NULL COMMENT '商品价格单位',
  `create_time` INT NULL COMMENT '创建日期',
  `update_time` INT NULL COMMENT '商品信息更新日期',
  `product_code` INT NULL COMMENT '商品编号',
  `thumb_1` VARCHAR(255) NULL COMMENT '缩略图1',
  `thumb_2` VARCHAR(255) NULL COMMENT '缩略图2',
  `thumb_3` VARCHAR(255) NULL COMMENT '缩略图3',
  `thumb_4` VARCHAR(255) NULL COMMENT '缩略图4',
  `description` MEDIUMTEXT NULL COMMENT '商品详情描述',
  `small_text` VARCHAR(50) NULL COMMENT '商品简介',
  `count` INT(11) NULL COMMENT '商品数量',
  `deduct` VARCHAR(5) NULL COMMENT '折扣：1-没有折扣，小于1有折扣',
  `category_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_category1_idx` (`category_id` ASC),
  CONSTRAINT `fk_product_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `ShopTest`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = gb2312
COMMENT = '商品信息表';


-- -----------------------------------------------------
-- Table `ShopTest`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShopTest`.`user_role` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '角色id 主键',
  `name` VARCHAR(20) NOT NULL COMMENT '角色名称\n',
  `create_time` INT NULL COMMENT '创建时间\n',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = gb2312
COMMENT = '用户角色表';


-- -----------------------------------------------------
-- Table `ShopTest`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShopTest`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '用户id 主键',
  `name` VARCHAR(45) NULL COMMENT '用户名',
  `phone` VARCHAR(15) NULL COMMENT '电话',
  `email` VARCHAR(100) NULL COMMENT '邮箱',
  `sex` VARCHAR(1) NULL COMMENT '性别',
  `header_icon` VARCHAR(255) NULL COMMENT '头像连接',
  `password` VARCHAR(45) NULL COMMENT '用户登录密码',
  `create_time` INT NULL COMMENT '创建时间',
  `user_role_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_user_role_idx` (`user_role_id` ASC),
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  CONSTRAINT `fk_user_user_role`
    FOREIGN KEY (`user_role_id`)
    REFERENCES `ShopTest`.`user_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = gb2312
COMMENT = '用户信息表';


-- -----------------------------------------------------
-- Table `ShopTest`.`user_has_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShopTest`.`user_has_product` (
  `user_id` INT(11) NOT NULL,
  `product_id` INT(11) NOT NULL,
  `create_time` INT NULL,
  PRIMARY KEY (`user_id`, `product_id`),
  INDEX `fk_user_has_product_product1_idx` (`product_id` ASC),
  INDEX `fk_user_has_product_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_has_product_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ShopTest`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_product_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `ShopTest`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = gb2312
COMMENT = '用户浏览过的商品';


-- -----------------------------------------------------
-- Table `ShopTest`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShopTest`.`address` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '地址id 主键\n',
  `detail` VARCHAR(255) NULL COMMENT '详细地址',
  `isdefault` TINYINT(1) NULL COMMENT '是否是默认地址',
  `phone` VARCHAR(15) NULL COMMENT '电话',
  `user_id` INT(11) NOT NULL,
  `recipients` VARCHAR(45) NULL COMMENT '收件人姓名',
  `create_time` INT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`),
  INDEX `fk_address_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_address_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ShopTest`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = gb2312
COMMENT = '地址表';


-- -----------------------------------------------------
-- Table `ShopTest`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShopTest`.`order` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '订单id',
  `order_code` VARCHAR(45) NOT NULL COMMENT '订单号',
  `state` VARCHAR(1) NULL COMMENT '订单状态：1-待付款，2-已付款，3-待发货，4-已发货，待收货，5-已收货，6-取消订单',
  `total_price` FLOAT NULL COMMENT '总金额 （元）',
  `create_time` INT NULL COMMENT '创建时间\n',
  `user_id` INT(11) NOT NULL,
  `express` VARCHAR(45) NULL COMMENT '快递',
  `express_code` VARCHAR(45) NULL COMMENT '快递编号',
  `address_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_user1_idx` (`user_id` ASC),
  INDEX `fk_order_address1_idx` (`address_id` ASC),
  CONSTRAINT `fk_order_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ShopTest`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `ShopTest`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShopTest`.`cart_has_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShopTest`.`cart_has_product` (
  `create_time` INT NULL,
  `count` INT NULL COMMENT '商品数量',
  `user_id` INT(11) NOT NULL,
  `product_id` INT(11) NOT NULL,
  INDEX `fk_cart_has_product_user1_idx` (`user_id` ASC),
  INDEX `fk_cart_has_product_product1_idx` (`product_id` ASC),
  CONSTRAINT `fk_cart_has_product_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ShopTest`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cart_has_product_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `ShopTest`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = gb2312
COMMENT = '购物车中的商品';


-- -----------------------------------------------------
-- Table `ShopTest`.`order_has_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShopTest`.`order_has_product` (
  `order_id` INT(11) NOT NULL,
  `product_id` INT(11) NOT NULL,
  `count` INT UNSIGNED NULL COMMENT '商品数量',
  `create_time` INT NULL,
  PRIMARY KEY (`order_id`, `product_id`),
  INDEX `fk_order_has_product_product1_idx` (`product_id` ASC),
  INDEX `fk_order_has_product_order1_idx` (`order_id` ASC),
  CONSTRAINT `fk_order_has_product_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `ShopTest`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_has_product_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `ShopTest`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = gb2312
COMMENT = '订单中的商品';


-- -----------------------------------------------------
-- Table `ShopTest`.`area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShopTest`.`area` (
  `idtable1` INT NOT NULL,
  `table1col` VARCHAR(45) NULL,
  `table1col1` VARCHAR(45) NULL,
  `table1col2` VARCHAR(45) NULL,
  PRIMARY KEY (`idtable1`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = gb2312
COMMENT = '区域表';


-- -----------------------------------------------------
-- Table `ShopTest`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShopTest`.`account` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `create_time` INT NULL,
  `sum` FLOAT NULL COMMENT '金额',
  `user_id` VARCHAR(45) NULL COMMENT '用户id，冗余字段',
  `state` VARCHAR(3) NULL COMMENT '支付状态:1-支付成功，2-支付失败，3-已退款',
  `order_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_account_order1_idx` (`order_id` ASC),
  CONSTRAINT `fk_account_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `ShopTest`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = gb2312
COMMENT = '账务信息表';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
